apiVersion: v1
kind: Service
metadata:
  labels:
    app: distcache-svc
  name: distcache-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5001
  selector:
    app: distcache
  type: ClusterIP