apiVersion: v1
kind: Service
metadata:
  labels:
    app: serfer-leader-svc
  name: serfer-leader-svc
spec:
  ports:
  - name: grpc
    protocol: TCP
    port: 443
    targetPort: 5001
  - name: serftcp
    protocol: TCP
    port: 7777
    targetPort: 7777
  - name: serfudp
    protocol: UDP
    port: 7777
    targetPort: 7777
  selector:
    app: serfer-leader
  type: ClusterIP